sudo: false
language: node_js
node_js: stable
env:
  matrix:
  - CMD=test
  - CMD=lint
matrix:
  fast_finish: true
  allow_failures:
  - env: MODE=lint
script:
- npm run $CMD
notifications:
  email: false
